#
# WorldGuard 的配置文件
#
# 关于编辑此文件：
# - 不要使用制表符（TAB）。你必须使用空格，否则 Bukkit 会报错。如果你
#   使用像 Notepad++ 这样的编辑器（推荐 Windows 用户使用），你需要
#   在 设置 > 首选项 > 语言 中配置 "将制表符替换为空格"。
# - 不要删除缩进。缩进用于将某些条目归类（例如 "enforce-single-session"
#   属于 "protection" 类别）。
# - 如果你想在放入 WorldGuard 之前检查此文件的格式，请将其粘贴到
#   http://yaml-online-parser.appspot.com/ 并查看是否给出 "ERROR:"。
# - 以 # 开头的行是注释，会被忽略。
#
# 警告：
# 请记得查看 WorldGuard 的兼容性表格，了解在当前版本的 Bukkit 中
# 是否有功能无法正常工作。
#

# -- 此处应被插件在游戏内自动替换 --